### ISSUE TITLE
Website Re-Design - Research and Product Design

### ISSUE THREAD

**Issue by tgeorgeux** [jupyter/jupyter.github.io#331] opened 2019-03-31 21:30 UTC
I've just returned from UCI this week where I have an opportunity to work with graduate students from UCI on their capstone project. The Capstone cycle for them is two quarters long (around 6 months). Given that Jupyter has limited design resources, I've asked them to work alongside the community to update the Jupyter.org website. The team is made up of four Students who are in UCI’s Informatics program; they have a combined 27+ years experience in UX, Design, and Development. I’ll let them introduce themselves below.

As some of you know, I started some background research on the website last year around this time, a task which was ambitious and went unfinished. I’ve asked the group to continue where I left off in terms of research, and to eventually write up a document that encodes some of the background, goals, vision, and direction of the Jupyter community/products. I’ve asked the team to keep the community updated with their progress, and they suggested a weekly update either here or on the Jupyter Discourse where they can update the status of work to get community input and feedback.

More updates to come over the next couple weeks as we all get into a good working groove. In the meantime, feel free to give them a warm Jupyter welcome! 

Schedule and Status (Expected Delivery Date):
### Research
- [x] Draft a Project Plan (April 1) 
- [x] Interview Protocol (April 1)
- [x] Heuristic Evaluation (April 1)
- [x]  Competitive Analysis (April 1)
- [x] Interviews (April 29)
- [x] Survey (April 22)
- [x] Affinity Diagrams (May 6)
- [x] Interview Synthesis (May 13)
- [x] Cognitive Walkthrough of existing website (May 6)
- [x] Develop Archetypes (May 6)
- [x] Design Principles (May 6)
- [x] MVP Feature Set (May 13)
- [x] Research Synthesis (May 13)

### Product Design
- [x] Information Architecture (May 27)
- [x] Style Guide (June 24)
- [x] Mockup (Wireframe) (May 27)
- [x] Low Fidelity Prototype (June 17)
- [x] Component Library (August 12)
- [x] Hight Fidelity Prototype (August 12)

### Final Deliverables
- [ ] Github Readme (August 12)
- [ ] Github Repository (August 12)
- [x] Final Report (Sept 1)

**Comment by daniellau** [comment] 2019-04-01 04:04
Hello everyone! My name is Daniel Lau and I’ll be the product manager for this endeavor. My background is in front end development and user experience design. I currently work as a UX Designer at Intuitive Surgical, where we make the Da Vinci surgical robot. I’m currently located in the San Francisco Bay Area. In my spare time, I enjoy eating at new restaurants, traveling to new countries, and spending time with friends and family. My favorite country I’ve recently visited is Japan.

I can’t wait to pick up where Tim left off and dive deep into researching Jupyter. This community is incredibly diverse and vibrant. Our team will focus on understanding Jupyter and developing a product that will make this community proud.

**Comment by jhornig** [comment] 2019-04-01 04:15
Hi everyone! My name is Joseph Hornig and I will be serving as the content strategist and assisting with UX research and design. It’s an honor to be working with Jupyter on this project and I’m looking forward to learning from you all as we go along.

I’m originally from the East Coast—I grew up in Baltimore, Maryland and then spent eight years in Washington, DC—but I love my new home in southern California. I’ve recently been hired as a UX Writer for Kaiser Permanente, and in my previous role I lead the website redesign for UCI’s [Office of Admissions](http://admissions.uci.edu/).

The HCI and Design master’s program has been an incredible experience so far, and I’m really excited to be partnering with Jupyter on this project. We’re hitting the ground running, so be on the lookout for updates from us soon!

**Comment by cmbui** [comment] 2019-04-01 05:05
Hi everyone! I'm Christina Bui, the lead researcher for this project. My background is in human-centered design research, from UC Berkeley's Design Innovation and UC Irvine's HCI programs. I'm currently signed on as a UI/UX & product marketing intern at Zuora, where my focus is on user research and market research. I was born and raised in southern California, but have spent the last 7 years in the San Francisco bay area. Having used Jupyter's products before, I've found the open source community inspiring in so many ways.

Thank you so much for the opportunity to contribute to this endeavor. We aim to drive Tim's project to fruition while bringing you all along in the spirit of openness and inclusion. Your feedback is crucial in steering our direction, so we look forward to hearing from you all!

**Comment by choldgraf** [comment] 2019-04-01 15:43
Hi all - looking forward to engaging with you in the coming weeks 👋

**Comment by iOmar2019** [comment] 2019-04-01 15:44
Hello team! I am Omar Filippelli the lead UX Designer for the project. I have 10+ years’ experience in UX design and usability research. Currently leading cloud development efforts for Panduit, one of the leading providers of Data Center hardware and software. I am excited with the opportunity to be part of Jupyter’s community and contribute to the success of this open-source product. This will be a great collaborative effort with your feedback, support, and contributions.  Something personal about me, I love watching and playing soccer. 

Happy to learn about the community, tool, and anything else related to Jupyter. Please feel free to reach out. 

@choldgraf Thanks for the heads up

**Comment by tgeorgeux** [comment] 2019-04-02 23:54
Good point @choldgraf I've started a discourse thread in the meta section.

https://discourse.jupyter.org/t/uci-graduate-students-working-jupyter-org/691

**Comment by Ruv7** [comment] 2019-04-09 00:45
Hello everyone. My name is Ana and I'm the Director of Jupyter work at Cal Poly in San Luis Obispo (I work with Tim). I look forward to seeing this work progress and to your contributions! I would encourage this group to engage/update the wider community of contributors as much as possible. One channel to keep in mind for big announcements to the larger community is Twitter which has a little over 40,000 followers. If you'd like to take advantage of this feel free to send me suggested content as you would like it published.

**Comment by cmbui** [comment] 2019-04-11 04:43
Thank you @choldgraf and @Ruv7 , we're excited to work with you all. Our initial research report is going to be posted in a few days, and we will definitely take you up on your offer to announce our updates as we release them.

Actually we are conducting 1-on-1 interviews for the next 2 weeks and would love to invite you to participate as contributors and steering council members. We have gathered a number of interviewees who are less active in the community, but we would like more perspectives from core members like yourselves. If you are or someone you know would be interested, feel free to message us to set up a call!

**Comment by Ruv7** [comment] 2019-04-11 17:18
Sure - is the week of the 22nd an option? Next week for me is pretty full with meetings. Send me a few times that work for you. Also if you pull together a 2 paragraph description I can send out a call for participation to the steering council. I would suggest 1 paragraph on who you are and your project, 1 paragraph on what you're looking for in the interview and the parameters. These are busy people so knowing the details of the ask will be important to determine whether or not they'll be able to participate. Note these folks are all over the world so definitely think about time zones when you're proposing meeting slots. :)

**Comment by jhornig** [comment] 2019-04-12 01:36
Thanks so much @Ruv7! The week of the 22nd should be fine, Tues/Wed/Thurs eves after 5:00 p.m. PST generally work best for us, but we're flexible. And if you wouldn't mind sharing the below invite with the Steering Council members, that would be great! Thanks so much for all of your help!

We are a group of Human-Computer Interaction graduate students at the University of California, Irvine who have partnered with Project Jupyter to help maximize the effectiveness of the jupyter.org website as part of our six-month capstone project. We are working directly with Tim George, Jupyter’s lead UI/UX designer, and have already begun some preliminary UX research.

To help learn as much as we can about Jupyter and its users, we would like to conduct a few one-on-one interviews with some members of the Steering Council. These interviews will allow us to have a more free-flowing conversation and dive deeper into certain topics as we go. Generally, we will want to know about how you got involved in Jupyter, why you use it, what you love about it, and what improvements you’d like to see made. 

We understand that you all are extremely busy, but if you can carve out roughly half an hour of your time to speak with one of us, we would really appreciate it! Among the four of us, we can generally accommodate any availability between 6:00 a.m. and 11:00 p.m. PST. Thanks so much for your support!

**Comment by jhornig** [comment] 2019-04-17 05:26
Hi everyone,

We have started the initial phase of our user research, and wanted to share with you all our findings so far. 

First, we conducted a heuristic evaluation, which involves benchmarking the effectiveness of the website against industry usability principles. Then we ran a competitive analysis against the websites of similar products. 

What we found is that Jupyter.org is doing a number of things well, including providing a breadth of useful and detailed Information, establishing credibility, and offering user flexibility, feedback, and ease-of-use. The issues we identified were shared by many of the competitors’ websites, such as minor bugs, some design inconsistencies, and missing calls-to-action.

Overall, the website is in great shape, and we have a preliminary roadmap for how we can make some improvements. For the next phase of our research, we will be conducting interviews, so please let us know if you’d be willing to speak with us for 30 minutes. [You can also fill out this brief survey](https://docs.google.com/forms/d/e/1FAIpQLScQcBH0LQPUQK2axtHjiMQuqUEtBBv82zsd11vyWYimKD4EMA/viewform?usp=sf_link).

Thank you to everyone who has helped out so far, and if you have any questions, please don’t hesitate to ask! ([The full report can be accessed here](https://drive.google.com/file/d/13d_Np-hTN2fIyxn02xjOSkJGdvdM0Jr4/view?usp=sharing).)


Team iO (UCI Capstone Group)

**Comment by Ruv7** [comment] 2019-04-17 18:48
@jhornig -  remind me, what is the best way for the Steering Council to reach out to you to schedule time?

**Comment by Ruv7** [comment] 2019-04-17 18:56
One more question as I'm pulling together the draft of this request: is this the program you're all in? Please send me the correct link if not.

https://mhcid.ics.uci.edu/

**Comment by tgeorgeux** [comment] 2019-04-17 20:55
@Ruv7 that is the correct link.

**Comment by tgeorgeux** [comment] 2019-04-17 20:57
@jhornig do you mind posting that schedule so those of us in the nosebleeds can follow along? Thanks for the work you're doing so far!

**Comment by Ruv7** [comment] 2019-04-17 22:33
Great, I shared the call for participation with the steering council earlier today. I asked folks to post here if they'd like to schedule time but if there is something else you prefer let me know and I can update the group with that detail.

**Comment by jhornig** [comment] 2019-04-18 23:46
@Ruv7 That would be perfect, thank you!

**Comment by jhornig** [comment] 2019-04-19 05:23
Here's our current [project timeline](https://drive.google.com/file/d/1w6l06QyNbO3JVcLHKkCNebvE6R-zvf5B/view?usp=sharing), let us know if you have any questions about it!

**Comment by jhornig** [comment] 2019-04-22 00:03
@Ruv7 if you wouldn't mind sharing a brief survey via the Jupyter Twitter, we would really appreciate it! 

To help guide a potential redesign strategy for jupyter.org, please fill out this brief survey about the data science tools you use. We appreciate your feedback! bit.ly/2IILpH8

**Comment by Ruv7** [comment] 2019-04-22 17:51
@jhornig - thanks for the timeline, I shared some feedback with Tim with the goal of making this more visible and useful to the community. For the tweet, the voice of the post needs to come from your group, not from Jupyter. Please re-word that to make some mention of your group. Something like, "We're happy to share that we are partnering with a design team at UC Irvine..." Or something like that.   This github issue should be in the survey intro also. In addition, I have some feedback on the survey wording and flow, has this already been activated/shared/launched? Not sure what to call it - basically are people already taking the survey?

**Comment by cmbui** [comment] 2019-04-23 02:37
@Ruv7  Joseph is working on re-wording the tweet and will get back to you on that. As for the survey, we actually have already begun taking in responses. We will look at the results at the end of this week to support our next research deliverables next week, but we will still gladly take any feedback you have for the wording and flow since we will keep the survey open for the duration of the whole project. Feel free to email me directly at cbui@berkeley.edu to discuss the survey. We've also just discussed with Tim on making the timeline more useful to the community to optimize the collaborative aspect of certain phases, so we will revise its representation based on that feedback. Thanks again for your help!

Also, just to keep everyone updated, we are wrapping up interviews this week and wanted to thank everyone who reached out and volunteered!

**Comment by afshin** [comment] 2019-04-23 12:12
I would love to participate. I can meet from 8:30AM to 9:00 AM PST tomorrow (Wednesday, 24 April). How should we speak? Is there a Zoom channel you are using?

**Comment by cbui2019** [comment] 2019-04-23 16:17
@afshin Thanks for reaching out! We're just scheduling interviewees with whichever team member has the availability that matches. Unfortunately, we don't have anyone available at 8:30 tomorrow morning. If you're still interested, email me at cbui@berkeley.edu and we can work out a different time/day. Otherwise, you can still help by filling out [our survey](https://bit.ly/2IILpH8). Data in all formats are valuable and appreciated! :)

We're also working on launching a usability test by the end of the week. We would appreciate any feedback on the tasks that will be asked of participants. Join our conversation on discourse [here](https://discourse.jupyter.org/t/wip-re-design-of-jupyter-org-website/691/15?u=cmbui)!

**Comment by cbui2019** [comment] 2019-04-23 16:20
@afshin Thanks for reaching out! We're just scheduling interviewees with whichever team member has the availability that matches. One of our team members is available for 8:30am tomorrow, so he'll reach out to you :)

We're also working on launching a usability test by the end of the week. We would appreciate any feedback on the tasks that will be asked of participants. Join our conversation on discourse [here](https://discourse.jupyter.org/t/wip-re-design-of-jupyter-org-website/691/15?u=cmbui)!

**Comment by iOmar2019** [comment] 2019-04-23 17:41
Hello Afshin,

This is Omar Filippelli. I will be taking the opportunity to interview you
tomorrow from 8:30 - 9:00 am PST. I normally use Skype for the interview,
but can switch to zoom if that is your preference. Let me know

Thank you!
Omar

**Comment by afshin** [comment] 2019-04-23 17:43
Hi @iOmar2019! Let's please use the "jupyter" channel on http://calpoly.zoom.us/

FYI, there is a call that begins on that channel at 9AM, but we should be fine.

Thanks very much!

**Comment by iOmar2019** [comment] 2019-04-23 17:45
sounds good, is there a login I need to host a meeting on
http://calpoly.zoom.us/? Also, I need to be able to record the conversation.

**Comment by afshin** [comment] 2019-04-23 17:48
I think @tgeorgeux can help you log in and record there.

**Comment by iOmar2019** [comment] 2019-04-23 17:49
Thanks!

**Comment by iOmar2019** [comment] 2019-04-24 15:33
Good morning Afshin. The calpoly.zoom requires a calpoly login with student
ID I don't have. Tim will be in another call this morning. do you think you
can start the call? It will let me join your call.

**Comment by afshin** [comment] 2019-04-24 15:39
Hi! Can we meet here for now? I don't have a way to record, unfortunately.

https://appear.in/jupyterlab

**Comment by iOmar2019** [comment] 2019-04-24 15:43
I am in

**Comment by jhornig** [comment] 2019-04-25 14:23
Hi @Ruv7, sorry for the late reply. Let me know if this would be adequate for Twitter: 

We're happy to share that we’ve partnered with a design team at UC Irvine to help guide a redesign strategy for jupyter.org. They need participants for a short survey, so if you have time to help with their research, they would really appreciate it! https://bit.ly/2IILpH8

**Comment by jhornig** [comment] 2019-04-25 14:28
Here’s an interesting insight from one of our interviews so far: “Jupyter basically invented the field. Data science could not be data science without it.” What do you all think about that?

**Comment by Ruv7** [comment] 2019-04-25 17:20
https://twitter.com/ProjectJupyter/status/1121462660388646912 - this went out, everyone please re-tweet and share with your followers.

**Comment by daniellau** [comment] 2019-04-25 19:10
Thanks so much @Ruv7. We're getting a lot of responses!

**Comment by jhornig** [comment] 2019-05-02 04:51
Here's our latest project plan.
![JupyterRedesignProjectPlan](https://user-images.githubusercontent.com/49138500/57057050-495a7700-6c5b-11e9-88d2-0c0824bd7682.png)

**Comment by tgeorgeux** [comment] 2019-05-02 22:40
I've updated the top level with deliverable dates. When I have a bit more time to organize files I'll drop in links to deliverables as appropriate.

**Comment by Ruv7** [comment] 2019-05-02 23:17
Excellent, thanks @jhornig and @tgeorgeux - this is good stuff.

**Comment by jhornig** [comment] 2019-06-04 03:53
We’ve been working really hard on the Jupyter website redesign, and as result we’ve fallen behind on updating you all about our progress. Our apologies. We want to spend this week catching you up on everything that we’ve done so far. 

First up is our affinity diagrams. We created two: one based on the functional needs of Jupyter, and one based on the emotional and social needs. All of these insights were gathered from our in-depth interviews with Jupyter users, non-users, contributors, and community members. The diagrams helped us create “jobs-to-be-done” for the website and the archetypes that we’ll be designing for. We’re going to share both of those later this week. 

Please let us know if you have any feedback!

![AffinityDiagram_Functional](https://user-images.githubusercontent.com/49138500/58850019-81c9e800-8641-11e9-9bd7-548f4257d0fc.jpg)

![AffinityDiagram_SocialEmotional](https://user-images.githubusercontent.com/49138500/58850027-89898c80-8641-11e9-9e4b-63a7017847b7.jpg)

**Comment by daniellau** [comment] 2019-06-04 16:41
Hey everyone! Here's another update for you all. We aggregated our interview data (using affinity diagrams) and formulated jobs to be done, the emotional, social, and practical needs the new Jupyter.org website needs to fulfill. 

We'll update you with our archetypes, cognitive walkthroughs, and sitemap later this week. 

![jupyter-jtbd-final](https://user-images.githubusercontent.com/598997/58897343-eec69780-86ac-11e9-9659-1dd234185a8b.png)

**Comment by choldgraf** [comment] 2019-06-04 17:59
This all looks really great, thanks for all of your hard work in putting this together!

Two quick constraints that I think we should consider as well and I didn't see in the jobs to be done:

* whatever the new site structure, it needs to be **maintained** by the Jupyter community over long periods of time. This means we need to optimize for workflows that are familiar to folks in the jupyter community (e.g. text files for content, and a separation of content from design). We should also (IMO) adopt a technology stack that is well-documented and relatively straightforward for Jovyans to learn.
* One of the most important roles of the jupyter website (IMO) is to direct people to *other* documentation in the jupyter ecosystem (on other domains, not jupyter.org). The documentation for each jupyter project will likely remain in their current states, and the website should be a way to answer the question "you want to learn more how to do XXX? you should go to this documentation page".

Hope those are helpful! Looking forward to seeing more updates as well!

**Comment by daniellau** [comment] 2019-06-05 16:30
Those are excellent points @choldgraf . We are definitely thinking about the modularity of jupyter.org. It will be built in a way that allows the community to easily update the website through pull requests. 

We also plan on leading people to the proper project documentation pages instead of having different sets of documentation. We'll keep making progress on this. We hope the sitemap will help clear things up.

**Comment by iOmar2019** [comment] 2019-06-05 20:58
Hi team! Following with our daily update routine. Here are the main archetypes considered for our redesign effort. These archetypes are modeled from a behavioral perspective. This is a great method for validating user flows and site navigation. It focuses on understanding who does what, when, and why, helping us determine our approach to prioritizing the features and ultimate user experience design for Jupyter.org 

As always, we are happy to get your early feedback and commentaries. Stay tune for our Cognitive Walkthroughs posting tomorrow.
<img width="2255" alt="Screen Shot 2019-06-05 at 12 13 55 PM" src="https://user-images.githubusercontent.com/49161481/58989857-8e615400-8799-11e9-8a12-6851f9694735.png">

**Comment by cmbui** [comment] 2019-06-07 06:46
Hi everyone! As Omar mentioned yesterday, here is a summary of our Cognitive Walkthrough. For context, CWs are basic interaction design exercises used to step into the shoes of a potential user and see how they might navigate the site based on their persona and hypothetical needs. In this case, we used the archetypes in Omar's post to approach Jupyter.org as first-time visitors. We tried our best to step into the shoes of these archetypes and used this exercise to help our understanding of the site's information architecture and possible user flows.

(Note: the archetype for "new user" is labeled as "visitor outside of data science" in this image)

![Jupyter CW Exercise](https://user-images.githubusercontent.com/49139217/59085987-3e77af80-88b5-11e9-9fe3-d2a86f8e50bb.jpg)

**Comment by grrbam** [comment] 2019-06-08 00:53
Hi friends! My name's Graham, and I was added to the MHCID team in the beginning of May!

I'm excited to show our first concept for a sitemap of the website redesign:
![jupyter_concept_sitemap](https://user-images.githubusercontent.com/31297568/59139999-04f28300-894d-11e9-9fc0-2768f5c8cef1.png)
 

Here's a brief explanation of each section with a little more detail than the graphic:

**Home**

- This page will be the landing page for jupyter.org, and act as an introduction to the mission and branding of Jupyter.

**About**

History

* This section will detail the history of the organization and project, including the mission of open-source computing and the goals of the organization.

Hall of Fame

* We envisioned this page as a way to showcase members of the community and entities that have done exceptional work towards Jupyter's goals

Governance

* This page will explain the governance of Jupyter as aqn organization, and link to members' GitHub handles, similar to the "Steering Council" section on the current website

Partnerships

* This page will house all information relating to partnerships with Jupyter, such as sponsorship and institutional partnership

**Projects**

Core

* We're really excited about this section, as we're designing an ecosystem in which each project has control over it's content and outreach. This will be a catalog of all core projects, including an overview of each project (and a list of their products), their team and contributors, and all the documentation for that project!

Orbit

* We also wanted to showcase all the projects out there that use Jupyter as a baseline! This page will be a catalog of those projects, linking to each of their unique pages

**Documentation**

* This page will hold links to all of Jupyter's documentation, including contributor and developer guides. The current website has these split, and we hope to streamline that flow for all users!

**Community**

Overview

* Jupyter is such a unique ecosystem of diverse communities built around the organization. We wanted a place to showcase that, and to allow new users to find communities they want to contribute to. This section will act as a catalyst for building each community out there!

Events

* This section will contain a calendar of events, and information on how people may volunteer with Jupyter and/or its various communities.

Blog

* Jupyter's fantastic blog will be showcased here!

We're so excited to continue to iterate through our design process, and  create a website that serves each and every one of you. Let us know what you think - we'll be coming back soon with much more!

**Comment by jhornig** [comment] 2019-06-13 01:43
Hey everyone,
We're playing around with some new taglines and descriptions and wanted to get your thoughts on our current drafts:

**Tagline:**
Compute together

**Description:**
Project Jupyter is a free suite of tools for computing openly, transparently, and collaboratively, built by and for a worldwide community.

Let us know what you think, thank you!

**Comment by choldgraf** [comment] 2019-06-13 03:44
This is a nice start! I think the word "interactive" should be in there. Interactive Computing is one of the things that ties together all of the tools in jupyter.

another thought is "data" or something along these lines should be in there as well, given that we are focusing on data analysis not computing in general

**Comment by Ruv7** [comment] 2019-06-14 00:45
Thanks all for this work! Responding to @grrbam on the site map, since partners make up the community of people/organizations who support our work, I would advise that the "partnerships" tab which exists currently in the "about us" be moved to "community". Putting this topic in the "about us" elevates it to a point which may not make sense. 

Regarding the tagline @jhornig - thanks for working on this, I would love to have this for our marketing! It will be tough to come up with one that feels right given all the many different use cases we have. Is there room in the timeline/task list to do further research on people's reactions or what is the plan here? This would be incredibly valuable output of this work but not sure it will get much feedback here. Quick note, from what I've seen open source software generally doesn't get pitched as "free" or no cost or any other term that refers to price, the marketing says simply "open source" and I suppose free is implied. Looking at taglines of other corporate entities that make a TON of different products for a ton of different types of users it seems like it leans toward something more cultural rather than trying to summarize what the thing is. That could be the direction to go in here though I would say that's not much easier than trying to solve the existing problem which is summarizing what Jupyter is in a catchy 3 - 4 word phrase. https://www.mycorporatelogo.com/10-corporate-giants-logos-and-taglines/ Open to your thoughts.

**Comment by jhornig** [comment] 2019-06-14 00:49
Thanks for your feedback @choldgraf! Two questions: it was mentioned to me that some folks make a distinction between "interactive computing" and "reproducible computing." Do you think there's value in trying to be more neutral in our language? And second, I think the word "computing" is generally understood (at least for the most part). But I worry that once you throw "interactive" in front of it, that it starts to become a bit jargon-y for the general public. What are your thoughts? Would love to hear others' input as well.

**Comment by jhornig** [comment] 2019-06-14 15:26
Hey @Ruv7, thanks for such a detailed response! The reason we threw "free" in there was because during our design jam with @tgeorgeux, we selected 'free' as one of the most important core values to individuals and contributors (more so than 'open'). So we were thinking it might be an important word that would stand out to people. But you're absolutely right that it's implied in "open source" (and everywhere else Jupyter is referred to as "open source") so I'm on board with making the switch back if we think it's more accurate.

Regarding the tagline, some of the research we did suggested that universally-known brands can get away with cultural/aspirational taglines, but lesser-known brands should lean toward a more descriptive tagline (though I'm happy to play with some aspirational taglines!). If this is something you would like to do further research on, I think we can accommodate for that. I'm happy to hop on a quick 15 min call to discuss further if you'd like.

**Comment by afshin** [comment] 2019-06-16 22:33
Whenever I use the word "free" to describe Jupyter, I use the construction "free as in speech" and also "free as in beer", where the main point is freedom, not cost. I *think* that's what the core value is meant to indicate.

**Comment by jhornig** [comment] 2019-06-18 14:37
Hi @Ruv7, Tim mentioned that you would be a good person to consult as we begin to develop content for the website. Would you have any time this week to hop on a quick 30 min call to go over tone, voice, and general editorial guidelines for Jupyter? Let me know, thanks! - Joseph

**Comment by Ruv7** [comment] 2019-06-18 18:01
@jhornig - I would ask that you reach out to Tim for my email. While we don't have defined editorial guidelines, I'm happy to answer questions and meet briefly. The content from the current website was created by an intern and or piecemeal by various people in the community. This is a gap in our resources. One person out in the Jupyter community that writes extensively about Jupyter is Tony Hirst. You can see some of his newsletters here: https://tinyletter.com/TrackingJupyter

**Comment by jhornig** [comment] 2019-06-18 21:29
Will do, thanks @Ruv7!

**Comment by jhornig** [comment] 2019-06-19 02:04
I wanted to share with everyone the first drafts of some new webpage copy that we've put together: 
Homepage: https://docs.google.com/document/d/1NW1YUWCy_VL7bTv8R1U4FsDFPTNvjY77waaLVqiOywU/edit?usp=sharing

History page:
https://docs.google.com/document/d/1ixWu9DHdk2DGw1qpgjhSBt_cVDYUxReaIXf9_7xTsdg/edit?usp=sharing

Please share your feedback by leaving comments or suggestions directly in the Google Docs.
Let us know if you have any questions. Thanks!

**Comment by cbui2019** [comment] 2019-06-22 19:40
Additionally, we're also beginning to do a product audit to get a better understanding of how to prioritize and categorize them. So if you guys can help us start by listing the products and grouping them in ways that make sense to you, that would be super helpful!

**Comment by cmbui** [comment] 2019-06-22 19:44
Additionally, we're also beginning to do a product audit to get a better understanding of how to prioritize and categorize them. So if you guys can help us start by listing the products and grouping them in ways that make sense to you, that would be super helpful!

**Comment by jhornig** [comment] 2019-07-05 17:10
Hi everyone,
We’re excited to show you our first round of low-fidelity prototypes for the new website. Please take a look and let us know what’s working well, what’s not quite working, and if we’re missing anything. We’re moving quickly with the design phase, so please share your feedback ASAP. 
Looking forward to hearing your thoughts!
![1-Homepage](https://user-images.githubusercontent.com/49138500/60736771-05ab1480-9f0d-11e9-9e17-0e6c9ddd999c.png)
![2-About](https://user-images.githubusercontent.com/49138500/60736773-05ab1480-9f0d-11e9-844b-dbeae1e97b8d.png)
![3-History](https://user-images.githubusercontent.com/49138500/60736774-05ab1480-9f0d-11e9-917b-42a08305dff7.png)
![4-Governance](https://user-images.githubusercontent.com/49138500/60736775-05ab1480-9f0d-11e9-9e74-4d6f5026a5c0.png)
![5-Products](https://user-images.githubusercontent.com/49138500/60736776-0643ab00-9f0d-11e9-987e-518fcf173a8a.png)
![6_JupyterLab](https://user-images.githubusercontent.com/49138500/60736777-0643ab00-9f0d-11e9-96f0-0b70a3aa7d59.png)
![7-JupyterHub](https://user-images.githubusercontent.com/49138500/60736779-0643ab00-9f0d-11e9-845f-ea43ddae8932.png)
![8-Documentation](https://user-images.githubusercontent.com/49138500/60736780-06dc4180-9f0d-11e9-8ea1-1cf4bc025e35.png)
![9-Community](https://user-images.githubusercontent.com/49138500/60736781-06dc4180-9f0d-11e9-8c7a-f3b749d7d74e.png)

**Comment by cmbui** [comment] 2019-07-27 01:32
Hi everyone,

We're trying to do some quick A/B testing to see how the general public would perceive and understand the content, and we're hoping you guys can help us recruit some test participants! (The tool we're using is called Lookback which will require a google chrome extension and can be easily removed after.) Here are the 2 versions of the website:

**Test A**
https://participate.lookback.io/LKcHQd

**Test B**
https://participate.lookback.io/A7zLAi

If you guys could send these tests out to any friends, family, or peers who are **unfamiliar** with Project Jupyter, that would be super helpful!

**Comment by minrk** [comment] 2019-07-30 06:35
Great work! I think this is really going to help folks.

Some quick feedback on the content:

I think using the Jupyter logo as the "O" in text is not in-line with the branding guidelines developed earlier. I seem to recall that we were trying to avoid different forms of the logo. Has that changed?

Text feedback (I hope this is the right time/place):

(Jupyter Products)

- I think "projects" is a better word than "products" in our community. Products has commercial implications that we don't share.
- "Empowering users to create and share with the world" is missing the direct object of "create."
- "frontend" and "front end" sometimes has a space, sometimes not (we all mix these up!). I think it probably shouldn't have a space.
- JupyterLab is not the latest Jupyter Notebook, it's the latest application or UI *for* Jupyter notebooks
- More than 100 programming languages mentioned here, "dozens" elsewhere. Maybe be consistent.


(JupyterLab)

Text gives the impression that JupyterLab replaces Jupyter notebooks, which is not accurate. JupyterLab is a new web UI *for* Jupyter notebooks. So while it is a successor to the "Jupyter Notebook" web application (confusing that both the application and the document had the same name, I know), it uses *the same* Jupyter notebook documents. I think this is a common misconception, and it's really important to communicate that JupyterLab "is a new application for working with the same Jupyter notebooks you know and love" and not a successor to Jupyter notebooks. 

A more accurate headline for JupyterLab  would be "The next generation application for your Jupyter Notebooks". The "Other Products" page has a more accurate description: "The next generation user interface for Jupyter". Maybe this same text should be everywhere.

(JupyterHub)

- "Create a shared Jupyter workspace" may give the wrong impression about sharing capabilities in JupyterHub (there are none, currently). A more accurate description is that JupyterHub gives each user *their own workspace* on shared computing resources.
- I'd avoid "same server" since it can be distributed across many machines. It may be too technical, but we usually use "computational resources" here.

How about:

> ## Bringing users and computers together

> JupyterHub allows multiple users to access notebooks and run code at the same time, each with their own documents and data, running on any shared computing resources, from a single server to the cloud to supercomputers.

Under Scalable, add "You can..." to indicate that this is an option, not a requirement. Alternately, add at the end "Or run with simple system users on a single shared server." Also probably mention "from small groups up to thousands of users" to communicate that it's really for small-to-large groups, not just large-to-even-larger.


This is excellent!

**Comment by jhornig** [comment] 2019-07-30 16:55
@minrk this is EXTREMELY helpful feedback, thank you for taking the time to go through everything so thoroughly!

**Comment by choldgraf** [comment] 2019-07-30 17:43
Just to build off of something that @minrk mentioned - I think another "core project" of the website should still be "The Jupyter Notebook". The notebook standard and kernel protocol are both really important parts of the project that are totally independent from the user interface (either the "classic interface" or jupyterlab / nteract). The website should highlight this IMO

**Comment by jhornig** [comment] 2019-08-29 04:55
Unfortunately, our time with this project is coming to end. Thank you for all of your support along the way, your insights and feedback were tremendously helpful.

We want to share with you our final designs. We hope they provide a good roadmap for future implementation. We are so excited to see the new jupyter.org once it’s finally ready.

Please feel free to reach out if you have any questions. Thanks again!

![Home](https://user-images.githubusercontent.com/49138500/63911209-6111f400-c9de-11e9-87fd-901175d44190.png)
![About](https://user-images.githubusercontent.com/49138500/63911218-68390200-c9de-11e9-83fc-a950255b8a2e.png)
![Technologies](https://user-images.githubusercontent.com/49138500/63911230-72f39700-c9de-11e9-88c9-f6a3be405a48.png)
![Documentation](https://user-images.githubusercontent.com/49138500/63911246-843ca380-c9de-11e9-883d-1c69c720bf20.png)
![Community](https://user-images.githubusercontent.com/49138500/63911252-8999ee00-c9de-11e9-9b92-e26abb6f2ebd.png)

**Comment by jhornig** [comment] 2019-08-29 04:57
![Jupyter Notebook](https://user-images.githubusercontent.com/49138500/63911326-bb12b980-c9de-11e9-8bfd-71fdc6138be2.png)
![JupyterLab](https://user-images.githubusercontent.com/49138500/63911332-be0daa00-c9de-11e9-9035-3cca9b08a058.png)
![JupyterHub](https://user-images.githubusercontent.com/49138500/63911340-c1089a80-c9de-11e9-935b-6e9e65ce06a6.png)
![Events](https://user-images.githubusercontent.com/49138500/63911344-c49c2180-c9de-11e9-8585-5707413651dd.png)

**Comment by Ruv7** [comment] 2019-09-13 19:58
Apologies to all for not responding sooner, I was having issues logging into GitHub and had to get some support to get back in. I want to say a huge THANK YOU to this entire team for this body of work. I see a large amount of potential in what you've created and I really really REALLY appreciate all your contributions.

**Comment by consideRatio** [comment] 2019-09-18 13:28
Wow this was really inspirational for me, to a jaw dropping extent! :heart: :tada: :+1:

**Comment by palewire** [comment] 2022-01-09 14:35
Since this ticket has gone more than two years without any activity, I'm going to close it. The work here remains impressive and will remain on file in the repository for potential future use.

**Closed by palewire** 2022-01-09 14:35 UTC
