### ISSUE TITLE
Shouldn't Jupyter display be left justified?

### ISSUE THREAD

**Issue by nickbadams** [jupyter/jupyter.github.io#101] opened 2016-06-07 00:25 UTC
I'm using Chrome 50. I'm trying to convert some R script into a Jupyter notebook and I'm finding that no matter how wide I make my Chrome window, Jupyter hugs the right side of the window, cutting off my (embarrassingly long) lines of code while the left side of the page is just white space. 

Hope it's (relatively) easy to make it left-justified, wrap the text, or fill the screen in some other way. 

Cheers!

![screenshot 2016-06-06 17 24 28](https://cloud.githubusercontent.com/assets/5760501/15842183/9973ea8e-2c0b-11e6-8bf8-2928cd3d2781.png)

**Comment by ellisonbg** [comment] 2017-10-09 02:19
This was relevant on the jupyter/notebook repo - the issue is fixed in our latest release there.

**Closed by ellisonbg** 2017-10-09 02:19 UTC
